name: knots

loader:
  _target_: src.data.loader.KnotDatasetLoader
  parameters:
    data_dir: ${paths.data_dir}
    data_name: knots
    csv_path: ${paths.data_dir}/knotinfo.csv
    target_column: ${task.col}
    label_shift: ${task.min_val}
    num_classes: ${task.num_classes}
    limit: null
    strict: false
    force_reload: false
    pre_transform:
      _target_: src.transforms.graph2cell_face_lifting.Graph2CellFaceLifting
      complex_dim: 2
      signed: false

split_params:
  proportions: ${split.proportions}
  seeds: ${split.seeds}

dataloader_params:
  batch_size: 32
  num_workers: 0
  pin_memory: false
