defaults:
  - _self_
  - dataset: knots
  - task: alternating
  - model: cwn
  - loss: classification
  - optimizer: adam
  - evaluator: classification
  - trainer: lightning
  - callbacks: default
  - logger: tensorboard
  - split: five_random
  - augmentation: none
  - hparams_search: null

experiment_name: tb_run
seed: 42

train: true
test: true
optimized_metric: val/accuracy

paths:
  root: ${oc.env:PWD}
  data_dir: ${paths.root}/data
  output_dir: ${paths.root}/outputs
  run_dir: ${paths.output_dir}/${experiment_name}/${task.name}/${model.name}/seed=${seed}

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${experiment_name}/${task.name}/${model.name}/seed=${seed}
  sweep:
    dir: outputs/${experiment_name}
    subdir: ${task.name}/${model.name}/seed=${seed}
